### PR TITLE
Remove Unneeded Text Improperly Merged into Master

### PR DESCRIPTION
**Pull request by lussierc**
This pull request fixes Issue #2.

I cannot revert the changes and do a normal force push to remove the unneeded commits because of the repository's current security system.

In order to fix this issue, I manually removed the improperly added lines from the `assessment.md` file.

### CODE REVIEW

**Review by koscinskic — APPROVED** [review]

**Review by corlettim — APPROVED** [review]

**Review by Cory-Wiard — APPROVED** [review]
I see a deletion of two lines that describes what Team 2 is covering. This should be approved because the two lines were deleted from the markdown because they were not needed.

**Comment by gkapfham** [comment]
Hello @lussierc, thanks for this work! I will approve it and then you can merge.

Finally, @lussierc, do you think that we should allow force pushing? If we did, then it would make it easier for you to run a `rebase` and then squash the commits and then do a force push. Please let me know what you think and don't forget to follow-on on this issue with the other project managers and technical leaders.

**Comment by gkapfham** [comment]
Hello @koscinskic, can you please add an icon or a photograph to your GitHub profile?

**Review by gkapfham — APPROVED** [review]
I approve this "revert" of the repository to handle the push to master that was accidentally made.

**Comment by lussierc** [comment]
> Finally, @lussierc, do you think that we should allow force pushing? If we did, then it would make it easier for you to run a `rebase` and then squash the commits and then do a force push. Please let me know what you think and don't forget to follow-on on this issue with the other project managers and technical leaders.

@gkapfham I feel that force pushing should be allowed as it would make it easier to fix issues like this in the future, where things are improperly merged into master, as we would not have to manually go into the code/markdown file and manually remove the content added by the commits of an improperly merged pull request, like I did for this PR. Then, instead of having the many unneeded commits from the improper merge and the additional commits from a `patch` PR (like this one) to fix them, we will just have commits that are truly relevant to the project in the master branch.

However, if there is a way to only allow certain people to force push, I feel this would be ideal as it would likely stop any improper force-pushing which could cause major problems within the repository. For instance, if this is possible only Technical Leaders, the course instructor, and maybe a few select team leaders/members on the project would be able to force push. If this isn't possible then I feel force pushing should be left off for the most part and only turned on when deemed necessary or ideal to fix a particular issue.

**Pull request merged**
